### ISSUE TITLE
Syntax error in apiquery.pm, line 46; ARM perl does not allow checking for default arguments.

### ISSUE THREAD

**Issue by R030t1** [rsu-client/rsu-client#110]
Hello, this is after adding the PPA and installing via apt. No error messages were produced after installation. I am using Xenial on arm64.

```WARNING: Running in fallback mode!
rsu-queries will use the system perl so some API calls
may not work until you install certain modules
WARNING: Wx::WebView module not found, API calls using Wx::WebView will not work

Use of uninitialized value $apicall in substitution (s///) at /opt/runescape/rsu/apiquery.pm line 43.
Use of uninitialized value $apicall in concatenation (.) or string at /opt/runescape/rsu/apiquery.pm line 46.
syntax error at (eval 45) line 1, at EOF
	...caught at /opt/runescape/rsu/apiquery.pm line 46.
```

EDIT: Not sure if it's better to reply to myself, or not. After some time I found what I think is the method I need to use to run the RS client (`rsu-query client.launch.launcher`). I would note it is not documented anywhere in the project, and that expecting users to globally install a program is not a good idea. I'm reimaging the SBC I was trying this with after the installation script somehow broke USB support. It would also be wise to not rely on system libraries and defer to the environment to find them. In the case of this script it seems to have found the location CPAN installed everything to though it reports it does not find the module.

**Comment by jmfgdev** [comment]
in "read this before making a new issue" @HikariKnight says to @ him so he'll get notified via email.
so basically, bump

**Comment by jmfgdev** [comment]
https://github.com/HikariKnight/rsu-client/issues/7

**Comment by HikariKnight** [comment]
@R030t1 i do not have an arm device to test this on anymore, but i know from earlier testing that arm devices have been a hit and miss, it works on some and not on others and there is no reason for why those lines get an uninitialized value because they are clearly created using

"my $apicall"

while i did have an arm device i tried to find out what caused this but i could not figure it out :|

**Comment by R030t1** [comment]
My apologies for not reading the README issue and not mentioning you. In any case, having reimaged my ODROID-C2 I can confirm that cloning your repository and passing parameters explicitly to `rsu-query` will launch RuneScape. Time permitting I will see if I can troubleshoot it, but my interest in the matter is waning as Hardkernel support for my device's Mali driver is lacking (only software rendering is available on the device I mentioned).

**Comment by jmfgdev** [comment]
@R030t1 @HikariKnight  I have 3  raspberry pi's, all different, the pi 1 2 and 3, I can test the software on each and give details if needed. In my experience the raspberry pi 3 on Ubuntu Mate wouldn't launch RSU. I have yet to try Raspbian. I imagine the raspberry pi 3 would still have some trouble chugging thru OSRS at anything higher than 1024x768 . I know little of the odroid-c2, but might check odroid out. I'll start up my raspberry pi 3 Ubuntu Mate and get the terminal output of launching runescape.

**Comment by R030t1** [comment]
@jmfgdev Unfortunately, RS on an embedded ARM device is probably not possible until the processors advance more (to be on par with low-end Intel devices of a few years ago) so that OpenGL can be done in software, or Jagex decides to implement an OpenGL ES renderer. Getting the script to work to the same level it does on x86(_64) is probably good work for the future.

It's kind of unfortunate because it seems unlikely that Jagex is using advanced OpenGL functionality. Personally I have no idea why they are separate interfaces and there is no failover from normal OpenGL to OpenGL ES. There are groups of people who have gotten old versions of RS decompiled and running using OpenGL ES but, needless to say, that won't work with the main game and is (for better or worse) illegal.

**Comment by jmfgdev** [comment]
@R030t1 It's possible, https://i.imgur.com/uVhBHT6.jpg. However a lot of tinkering is required, and Proprietary Oracle Sun Java seems to be the only one to run well. I'm confused, you said you managed to get the script to launch in your last comment. I've seen it working alright. Is it impossible or not?

**Comment by HikariKnight** [comment]
@R030t1 @jmfgdev yes from what i remember jagex implementation of openGL is not supported on arm and most likely will not be without hacking it together yourself (which would be walking in the grey area of the 3rd party tools ruleset they have if i were to guess so)

hence why arm is not officially supported, plus the fact the scripts seems to work flawlessly on once device and fail on checking for no arguments on others or just getting random errors that shouldn't trigger because it runs fine everywere else etc.

the projects main scope is just to get the client "runnable" on as many platforms as possible where playability is focused on x86 and x86_64/amd64 platforms as those are officially supported environments. all other environments other than those officially supported just serve as proofs of concept, like when i modified my wii to be able to run the client, it wasnt playable and it did crash after 2 minutes ingame but hey i did make it run ;)

although i think i did hear rumors at one point in early development that it was working fine on sparc processors but do not quote me on that as thats quite a few years ago now.

**Comment by jmfgdev** [comment]
@HikariKnight I took the picture we were talking about from imgur and put the link into Anonimag.es and hopefully you can see this one? https://anonimag.es/i/uVhBHT69fa1f.jpg
I also downloaded the original file from imgur and drag and dropped it here. If you can't see the picture you might be on AOL browser. =P
![uvhbht6](https://cloud.githubusercontent.com/assets/25621994/23519165/f698054a-ff43-11e6-8f2b-f828000f12f1.jpg)

**Comment by HikariKnight** [comment]
@jmfgdev nice!
figured it had to be oldschool :)

also i see you got my old keyboard, with the same amount of dust too XD
