### ISSUE TITLE
chromebook c720

### ISSUE THREAD

**Issue by nirnble** [rsu-client/rsu-client#119]
im a total noob to this all i want to do is run osrs on my chromebook c720 in a linux that works please help me

**Comment by nirnble** [comment]
@HikariKnight

**Comment by HikariKnight** [comment]
@nirnble hi
there is no official support for the chromebooks due to some oddities with how the scripts run on some chromebooks so i cant really help either as i do not own a chromebook either.

**Comment by ChaosCat** [comment]
@nirnble I have a lot of Chromebooks in the educational institute I'm currently enrolled at and as one of the technical lead team there, I experiment with them to see how extensive is the access to the system by regular users. The question at hand is, what do you mean by installing the client and it's packages on the system?
Do you mean you want to run OSRS natively on ChromeOS? If that's the case then, unfortunately, it's not really possible.
there are very few packages which you can download even with full developer access and you would have a **very** tough time resolving dependency issues if you plan on installing the (massive amount of) packages required to run the client manually *since there is no package manager which supports ChromeOS natively*.

So, is it entirely impossible? *No*.
Your best bet is to install some other OS such as Ubuntu using Crouton for example, which then, with some configuration, you can run alongside chromeOS (not even dual boot, literally switch between them using a shortcut) and then you can install all the packages normally.

**Comment by HikariKnight** [comment]
closing this as its not had any info since last year
