### ISSUE TITLE
The following signatures were invalid

### ISSUE THREAD

**Issue by TheMysticalTaco** [rsu-client/rsu-client#146]
I did
sudo apt-add-repository ppa:hikariknight/unix-runescape-client
once it finished i did
sudo apt-get update && sudo apt-get install unix-runescape-client
Now it keeps giving me 
W: GPG error: https://content.runescape.com/downloads/ubuntu trusty InRelease: The following signatures were invalid: AAC9264309E4D717441DB9527373B12CE03BEB4B
E: The repository 'https://content.runescape.com/downloads/ubuntu trusty InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
What do i do?

**Comment by abacefbeca** [comment]
Might've helped if you had included what distro and version you are using. Anyway, looks like the signature was rejected because it is based on SHA1 which is no longer secure because of some issues. A better signature needs to be provided or maybe you can set your system to ignore the signature issue with that particular PPA. Though, getting a better signature is the better solution.

**Comment by HikariKnight** [comment]
I can no longer update packages in trusty so you will have to either
1. use a newer distribution
2. use a newer branch (example, edit every instance of trusty into "bionic" inside "/etc/apt/sources.list.d/hikariknight-ubuntu-unix-runescape-client-trusty.list"
PLEASE NOTE THIS IS NEVER STANDARD PRACTICE AND SHOULD NEVER BE DONE ON OLDER DISTRIBUTIONS UNLESS THE DEVELOPER CAN CONFIRM THE DEPENDENCY LIST IS NOT VERSION DEPENDENT OR THE PPA DOES NOT CONTAIN ANY PACKAGES THAT OTHERWISE IS AVAILABLE THROUGH THE MAIN REPOSITORY!)

either way the trusty branch is no longer accepting new submissions so i cannot update it.

**Comment by abacefbeca** [comment]
@HikariKnight 
Actually, the error message TheMysticalTaco is asking about involves Jagex's repository for their NXT client. It doesn't involve the RSU client launcher but I guess he thought it involved the RSU client launcher because he saw the message while following instructions for the RSU client launcher. Jagex needs to use something better than SHA1 for their signature.

**Comment by HikariKnight** [comment]
oh right @abacefbeca i misread it last night
jagex is most likely never going to maintain that repository properly, so the best solution right now is to use the flatpak someone made of the client

https://flatpak.org/
https://flathub.org/apps/details/com.jagex.RuneScape

you might have to add
`PULSE_LATENCY_MSEC=185`
in front of the launch command in the menu entry to fix some possible audio issues (might need to tweak the numbers)
